# Hardcoded Jupyter's python3 bin path to use the same package set when running in the terminal.

# Code generated by conversation:
# https://claude.ai/share/4445186e-dbe1-4574-b512-a01b79512644

import json
import sys
import textwrap

def pretty_print_conversation(json_file_path: str) -> None:
  with open(json_file_path, "r") as f:
    data = json.load(f)

  suite = data.get("suite_name", "unknown")
  pipeline = data.get("pipeline_name", "unknown")
  task_id = data.get("user_task_id", "unknown")
  utility = data.get("utility")
  security = data.get("security")

  print("=" * 70)
  print(f"  Suite: {suite}  |  Pipeline: {pipeline}  |  Task: {task_id}")
  print(f"  Utility: {utility}  |  Security: {security}")
  print("=" * 70)
  print()

  for msg in data.get("messages", []):
    role = msg.get("role", "unknown").upper()

    # Extract text content
    content_blocks = msg.get("content", [])
    if isinstance(content_blocks, list):
      text = " ".join(
        block.get("content", block.get("text", ""))
        for block in content_blocks
        if isinstance(block, dict)
      ).strip()
    else:
      text = str(content_blocks).strip()

    # Extract tool calls
    tool_calls = msg.get("tool_calls") or []

    # Role header
    role_labels = {
      "USER": "👤 USER",
      "ASSISTANT": "🤖 ASSISTANT",
      "SYSTEM": "⚙️  SYSTEM",
      "TOOL": "🔧 TOOL RESULT",
    }
    label = role_labels.get(role, f"[{role}]")
    print(f"{label}")
    print("-" * 70)

    # Print text body
    if text:
      for line in textwrap.wrap(text, width=66):
        print(f"  {line}")

    # Print tool calls (assistant invoking tools)
    for call in tool_calls:
      fn = call.get("function", "?")
      args = call.get("args", {})
      print(f"  → Tool call: {fn}({json.dumps(args, ensure_ascii=False)})")

    # Print tool result metadata (which call this result belongs to)
    if role == "TOOL":
      linked_call = msg.get("tool_call", {})
      if linked_call:
        fn = linked_call.get("function", "?")
        args = linked_call.get("args", {})
        print(f"  ↳ Result for: {fn}({json.dumps(args, ensure_ascii=False)})")

    print()

if __name__ == "__main__":
  pretty_print_conversation(sys.argv[1])

